name: build astro site

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [deploy]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3

      - name: generate
        run: |-
          ls
          npm install
          npm run build
          ls

      - name: push to the repo
        run: |-
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "bot: auto generation"
          git push
